from dataclasses import replace

from textual.theme import BUILTIN_THEMES, Theme


BUN_THEME: Theme = replace(
    BUILTIN_THEMES["flexoki"],
    name="bun-carbon",
    primary="#F6F5F8",
    secondary="#898989",
    warning="#EEB240",
    error="#C65F5F",
    success="#7FB77E",
    accent="#EEB240",
    foreground="#F4F4F4",
    background="#101010",
    surface="#1E1E1E",
    panel="#343434",
    boost="#1A1A1A",
    dark=True,
    variables={
        "primary-muted": "#D0CFD2",
        "secondary-muted": "#4A4A4A",
        "accent-muted": "#7A5D24",
        "warning-muted": "#7A5D24",
        "error-muted": "#5A2E2E",
        "success-muted": "#355236",
        "text": "#F4F4F4",
        "text-muted": "#898989",
        "text-disabled": "#525252",
        "foreground-muted": "#898989",
        "foreground-disabled": "#525252",
        "text-primary": "#222223",
        "text-secondary": "#898989",
        "text-warning": "#222223",
        "text-error": "#F4F4F4",
        "text-success": "#F4F4F4",
        "text-accent": "#222223",
        "border": "#343434",
        "border-blurred": "#1E1E1E",
        "surface-active": "#343434",
        "block-cursor-foreground": "#222223",
        "block-cursor-background": "#F6F5F8",
        "block-cursor-text-style": "none",
        "block-cursor-blurred-foreground": "#F4F4F4",
        "block-cursor-blurred-background": "#343434",
        "block-cursor-blurred-text-style": "none",
        "block-hover-background": "#1A1A1A",
        "scrollbar": "#343434",
        "scrollbar-hover": "#525252",
        "scrollbar-active": "#EEB240",
        "scrollbar-background": "#101010",
        "scrollbar-background-hover": "#101010",
        "scrollbar-background-active": "#101010",
        "scrollbar-corner-color": "#101010",
        "link-background": "transparent",
        "link-background-hover": "#EEB240",
        "link-color": "#F4F4F4",
        "link-color-hover": "#222223",
        "link-style": "underline",
        "link-style-hover": "bold",
        "button-foreground": "#F4F4F4",
        "button-color-foreground": "#222223",
        "button-focus-text-style": "bold",
        "footer-background": "#343434",
        "footer-foreground": "#F4F4F4",
        "footer-key-foreground": "#EEB240",
        "footer-description-foreground": "#F4F4F4",
        "footer-key-background": "transparent",
        "footer-description-background": "transparent",
        "footer-item-background": "transparent",
        "input-cursor-background": "#F4F4F4",
        "input-cursor-foreground": "#222223",
        "input-cursor-text-style": "none",
        "input-selection-background": "#343434",
        "markdown-h1-color": "#F4F4F4",
        "markdown-h1-background": "transparent",
        "markdown-h1-text-style": "bold",
        "markdown-h2-color": "#F4F4F4",
        "markdown-h2-background": "transparent",
        "markdown-h2-text-style": "bold",
        "markdown-h3-color": "#F4F4F4",
        "markdown-h3-background": "transparent",
        "markdown-h3-text-style": "bold",
        "markdown-h4-color": "#F4F4F4",
        "markdown-h4-background": "transparent",
        "markdown-h4-text-style": "bold",
        "markdown-h5-color": "#F4F4F4",
        "markdown-h5-background": "transparent",
        "markdown-h5-text-style": "bold",
        "markdown-h6-color": "#898989",
        "markdown-h6-background": "transparent",
        "markdown-h6-text-style": "bold",
        "app-button-disabled-background": "#1A1A1A",
        "app-button-disabled-foreground": "#525252",
    },
)
